name: Build Windows Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 关键：用低版本 Flutter 匹配 intl 0.18.1
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: stable
          cache: true

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: |
          cd simple_live_app
          flutter pub get

      - name: Build Windows
        run: |
          cd simple_live_app
          flutter build windows --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleLive-Windows
          path: simple_live_app/build/windows/runner/Release/
